name: Build TailwindCSS

on:
  push:
    paths:
      - "**.jinja"
      - "**.css"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Tailwind CSS and dependencies
        run: npm install -D tailwindcss postcss autoprefixer

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./muicebot_plugin_status/static/css/input.css -o ./muicebot_plugin_status/static/css/output.css --minify

      - name: Commit Tailwind CSS
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add ./muicebot_plugin_status/static/css/output.css

            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git commit -m "Update Tailwind CSS" || echo "No changes to commit"
            git push